import MainView from "components/pages/main/MainView";
import WideScreenImage from "components/pages/main/WideScreenImage";
import type { NextPage } from "next";
import Head from "next/head";
import ContentWrapper from "../components/layout/wrappers/ContentWrapper";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Les Délices de Marie Lou</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <div style={{height:'0vh'}}></div>
                <WideScreenImage />
                <ContentWrapper>
                    <MainView />
                </ContentWrapper>
            </main>
        </div>
    );
};

export default Home;
