import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import ScreenWideImage from "../components/layout/image/ScreenWideImage";
import ContentWrapper from "../components/layout/wrappers/ContentWrapper";
import FoodGallery from "../components/pages/main/FoodGallery";
import LesDelicesDescription from "../components/pages/main/LesDelicesDescription";
import styles from "../styles/Home.module.scss";
// add bootstrap css

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Les Délices de Marie Lou</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <ScreenWideImage
                    src="/boutique_large.jpeg"
                    alt="accueil les delices de marie lou"
                    maxHeight="400px"
                    objectPosition="50% 20%"
                />
                <ContentWrapper>
                    <LesDelicesDescription />
                    <FoodGallery />
                </ContentWrapper>
            </main>
        </div>
    );
};

export default Home;
